name: reconciliation_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  sqflite_common_ffi: ^2.3.4+4
  file_picker: ^8.0.0+1
  spreadsheet_decoder: ^2.3.0
  uuid: ^4.3.3
  syncfusion_flutter_xlsio: ^29.2.11
  excel: ^2.1.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true